### ISSUE TITLE
Missing date

### ISSUE THREAD

**Issue by oifj34f34f** [ticky/wayback-classic#29]
February 24, 2024 is missing from [Wayback Classic](https://wayback-classic.net/cgi-bin/history.cgi?q=https://kisslinux.org/&date=202402&utf8=%E2%9C%93), but available [here](https://web.archive.org/web/20240000000000*/https://kisslinux.org/)

**Comment by oifj34f34f** [comment]
It seems to be a query issue:

```sh
curl 'https://web.archive.org/cdx/search/cdx?url=https://kisslinux.org/&output=json&from=202402&to=202402&collapse=digest'
```

```json
[
    [
        "urlkey",
        "timestamp",
        "original",
        "mimetype",
        "statuscode",
        "digest",
        "length"
    ],
    [
        "org,kisslinux)/",
        "20240205160757",
        "https://kisslinux.org/",
        "warc/revisit",
        "-",
        "AQ23MLDHMGYAJZ2VEVXD2JIY2L6SHNUD",
        "848"
    ]
]

```

**Comment by ticky** [comment]
Hi @oifj34f34f thanks for digging into that! This stems from the use of the `collapse=digest` option, which [asks the CDX API to only return unique results](https://github.com/internetarchive/wayback/blob/master/wayback-cdx-server/README.md#collapsing).

If you request without that option, you get three entries for that period:

```json
[["urlkey","timestamp","original","mimetype","statuscode","digest","length"],
["org,kisslinux)/", "20240205160757", "https://kisslinux.org/", "warc/revisit", "-", "AQ23MLDHMGYAJZ2VEVXD2JIY2L6SHNUD", "848"],
["org,kisslinux)/", "20240205160757", "https://kisslinux.org/", "warc/revisit", "-", "AQ23MLDHMGYAJZ2VEVXD2JIY2L6SHNUD", "848"],
["org,kisslinux)/", "20240224161022", "https://kisslinux.org/", "text/html", "200", "AQ23MLDHMGYAJZ2VEVXD2JIY2L6SHNUD", "5200"]]
```

Note that they all have the same digest of `AQ23MLDHMGYAJZ2VEVXD2JIY2L6SHNUD`, meaning their underlying page contents are the same.

I agree that this is inconsistent with web.archive.org's UI, though this was an intentional choice to avoid presenting redundant snapshots on memory- and bandwidth-restricted clients.

Let me know what you think; adding an option to show these snapshots would be feasible, but I am not sure if it would be particularly useful.

**Comment by oifj34f34f** [comment]
@ticky Thanks for the reply, it makes sense!
