### ISSUE TITLE
Problems trying to download any file when using a Dreamcast Web browser

### ISSUE THREAD

**Issue by joelos1111** [ticky/wayback-classic#31]
I'm having problems when trying to download any file through the wayback-classic website but this issue happens only when i use any Sega Dreamcast Web Browser because when i use Google Chrome even from my android phone i can download normally to my desktop without any problem whatsoever whatever file from the past that i want to. I tried various Dreamcast browsers even the latest version of the XDP web browser and it always fails when downloading any file no matter the date you choose. I don't know if i need to do something else to be able to download files directly to the Dreamcast VMU but i would like you to tell me please what steps should i follow in order to download for example a .VMU save file directly to the Dreamcast?. I attach here a screenshot so you can analize it and try to correct this issue.
![Screenshot_20240515-062551_Flycast](https://github.com/ticky/wayback-classic/assets/113259459/b28e4990-8267-4165-8be6-0bc3793ce10c)
![Screenshot_20240515-062537_Flycast](https://github.com/ticky/wayback-classic/assets/113259459/c08793c1-ce54-4257-a0de-27ebb4bcec0a)

**Comment by ticky** [comment]
Hi @joelos1111, I'm sorry to say that due to a design flaw in Sega's VMI file format it is unlikely that the Wayback Machine holds the data you are seeking.

The files on the VMU require several bits of Dreamcast-specific metadata which can't be held normally by computers, so Sega were left with two choices; make a new format which added that metadata to a separate file which pointed at the data file, or to make a new format which contained both. They chose the former, presumably because it means they don't have to do any additional processing of the file content when downloading.

This resulted in the VMI format you're attempting to use here; it is in fact a small (460 bytes in your case!) file which contains _just_ the Dreamcast-specific metadata (i.e. whether the file should be allowed to be copied, and an assortment of other things) and points at a matching _VMS_ file which contains the actual save data you're seeking.

Sadly, because the VMI file was a non-standard format, and doesn't itself contain the save data, it is unlikely the Wayback Machine's crawler _knew_ the VMS file existed, let alone was necessary for the Dreamcast download to function.

In your case, with the file at [dreamcast.planetweb.com/gamers/saves/resident_evil/v49956.vmi ](http://wayback-classic.net/cgi-bin/history.cgi?q=dreamcast.planetweb.com%2Fgamers%2Fsaves%2Fresident_evil%2Fv49956.vmi&date=200605&utf8=✓) there sadly [isn't a matching VMS file archived](http://wayback-classic.net/cgi-bin/history.cgi?q=dreamcast.planetweb.com%2Fgamers%2Fsaves%2Fresident_evil%2Fv49956.vms&utf8=✓), and the Dreamcast browser will show the somewhat unhelpful error you're experiencing.

It's a shame this decision means a lot of this data is not present in web archives like the Wayback Machine without access to an _actual_ time machine.

---

All that being said, it looks like there _is_ another, Dreamcast-specific archive of saves, including this one (it's right at the top!), maintained by Bucanero: http://www.bucanero.com.ar/dreamcast/vmu/resident_evil/

Keep dreaming :)
